sudo: required
services:
  - docker
before_install:
  - docker build -t kareemelkasaby/multi-app -f ./client/Dockerfile.dev ./client
script:
  - docker run kareemelkasaby/multi-app npm run test -- --coverage
after_success:
  - docker build -t kareemelkasaby/multi-nginx ./nginx
  - docker build -t kareemelkasaby/multi-client ./client
  - docker build -t kareemelkasaby/multi-server ./server
  - docker build -t kareemelkasaby/multi-worker ./worker
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker push kareemelkasaby/multi-nginx 
  - docker push kareemelkasaby/multi-client
  - docker push kareemelkasaby/multi-server
  - docker push kareemelkasaby/multi-worker
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-808277092346"
    bucket_path: "multi-docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"

